sudo: required

services:
  - docker

before_install:
  - docker build -t rumi/docker-reactjs -f Dockerfile.dev .

script:
  - docker run -e CI=true rumi/docker-reactjs npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-978149335856"
  bucket_path: "frontend"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

cache:
  directories:
    - node_modules
