sudo: required

services:
  - docker

before_install:
  - docker build -t rumi/docker-reactjs -f Dockerfile.dev .

script:
  - docker run -e CI=true rumi/docker-reactjs npm run test

cache:
  directories:
    - node_modules
